// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@repo/ui/navbar";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-zinc-200 text-black">
        <Navbar />
        <main>
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
